config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users

  resources :answers, only: [:update, :destroy]

  resources :questions do
   resources :answers, only: [:create]
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :question,
    presence: true

  validates :user,
    presence: true

  validates :body,
    presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, uniqueness: { scope: :user_id }

  validates :title,
    presence: true,
      length: { minimum: 40 }

  validates :description,
    presence: true,
      length: { minimum: 150 }

  validates :user,
    presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :questions
  has_many :answers

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user = current_user
    if @answer.save
      flash[:notice] = "Answer added successfully"
      redirect_to question_path(@question)
    else
      render 'questions/show'
    end
  end

  def update
    @answer = Answer.find(params[:id])
    if @answer.update(answer_params)
      flash[:notice] = "Answer edited successfully"
      redirect_to question_path(params[:answer][:question_id].to_i)
    else
      @question = Question.find(params[:answer][:question_id].to_i)
      render template: 'questions/show'
    end
  end

  def destroy
    @answer = Answer.find(params[:id])
    @question = @answer.question
    Answer.delete(@answer)
    flash[:notice] = "Answer deleted!"
    redirect_to question_path(@question)
  end

protected
  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :user_name
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update, :destroy]

  def index
    @questions = Question.page(params[:page]).order(created_at: :desc)
  end

  def show
    if params[:question_id]
      @question = Question.find(params[:question_id])
      @answer   = Answer.find(params[:id])
    else
      @question = Question.find(params[:id])
      @answer   = Answer.new
    end
  end

  def new
    @question = Question.new
  end


  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "New question added successfully"
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Question edited successfully"
      redirect_to questions_path
    else
      render :edit
    end
  end

  def destroy
    Answer.where(question_id: params[:id]).destroy_all
    Question.delete(params[:id])
    flash[:notice] = "Question deleted!"
    redirect_to questions_path
  end

protected
  def question_params
    params.require(:question).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown
    # options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    # syntax_highlighter(Redcarpet.new(text, *options).to_html).html_safe
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
  end

  def syntax_highlighter(html)
    doc = Nokogiri::HTML(html)
    doc.search("//pre[@lang]").each do |pre|
      pre.replace Albino.colorize(pre.text.rstrip, pre[:lang])
    end
    doc.to_s
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='nav-bar'>
    <ul>
      <li><h2 class='nav-bar-links'><%= link_to 'Rescue Mission', root_path %></h1></li>
      <li><h5 class='nav-bar-links'><%= link_to 'New question', new_question_path %></h5></li>
      <% if user_signed_in?%>
        <li class='user-links'><h5 class='nav-bar-links'><%= link_to 'Log out', destroy_user_session_path, method: :delete %></h5></li>
      <% else %>
        <li class='user-links'><h5 class='nav-bar-links'><%= link_to 'Sign in', new_user_session_path %></h5></li>
        <li class='user-links'><h5 class='nav-bar-links'><%= link_to 'Sign up', new_user_registration_path %></h5></li>
      <% end %>
    </ul>
  </div>


<div class='row'>
  <% if notice %>
    <div class="notice devise"><%= notice %></div>
  <% end %>
  <% if alert %>
    <div class="alert devise"><%= alert %></div>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/questions/_form.html.erb
<% if @question.errors.present? %>
  <div id='errors'>
    <ul>
      <% @question.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @question do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
    <%= f.hidden_field :user_id, value: current_user.to_param %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<fieldset>
  <legend>Edit question</legend>

  <%= render partial: "form", object: @question %>

</fieldset>
<div class='row'>
  <div class='small-1 column delete-question'>
    <%= link_to 'Delete', question_path(@question.to_param), method: :delete %>
  </div>
  <div class='small-11 columns'></div>
</div>

app/views/questions/index.html.erb
<h3>Users Questions</h3>

<ul>
<% @questions.each do |question| %>
  <li class='question-element'>
    <div class='row questions-container'>
      <h4><%= link_to question.title, question_path(question.to_param), method: :get %></h4>
      <p><%= "#{question.user.user_name} | Answers: #{question.answers.length} | Best answer by" %></p>
    </div>
  </li>
<% end %>
</ul>

app/views/questions/new.html.erb
<fieldset>
  <legend>New question</legend>

  <%= render partial: "form" %>

</fieldset>

app/views/questions/show.html.erb
<% if @question.user == current_user %>
    <div class='title-buttons'>
      <%= link_to 'Edit Question', edit_question_path(@question.to_param), method: :get %>
    </div>
    <div class='title-buttons'>
      <%= link_to 'Delete', question_path(@question.to_param), method: :delete %>
    </div>
<% end %>

<h6><%= "#{@question.user.user_name} | #{@question.created_at}" %></h6>
<h3 id='question-title'><%= @question.title %></h3>

<fieldset>
  <legend>description</legend>
  <p><%= markdown.render(@question.description).html_safe %></p>
</fieldset>

<% if !@question.answers.empty? %>
  <h4>Answer(s)</h4>
  <% count = 0 %>
  <% @question.answers.order(:created_at).each do |answer| %>
    <fieldset>
      <legend><%= answer.user.user_name %></legend>
        <div class='answer-edit answer-<%= count %>'>
          <p><%= markdown.render(answer.body).html_safe %></p>
        </div>

        <% if answer.user == current_user%>

          <div>
            <div class='answer-button edit edit-<%= count %>'>
              <%= link_to 'Edit', '#', name: count %>
            </div>
            <div class='answer-button delete-<%= count %>'>
              <%= link_to 'Delete', answer_path(answer), method: :delete %>
            </div>
          </div>

          <div class='form-edit form-edit-<%= count %>'>
          <%= form_for answer do |f| %>

            <div class="field">
              <%= f.text_area :body %>
            </div>

            <div class="actions">
              <%= f.submit %>
              <div class='answer-button cancel'>
               <%= link_to 'Cancel', '#', name: count %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </fieldset>
    <% count += 1 %>
  <% end %>
<% end %>

<fieldset>
  <legend>New Answer</legend>
  <% if @answer.errors.present? %>
    <div id='errors'>
      <ul>
        <% @answer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for [@question, @answer] do |f| %>
    <div class="field">
      <%= f.text_area :body %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
</fieldset>